# Generated by Django 2.0.2 on 2019-08-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
